### ISSUE TITLE
Unpack.py problem

### ISSUE THREAD

**Issue by Kiri0824** [zzj1111/Preprocessed-CMLR-Dataset-For-Wav2Lip#3]
i'm preprocessing the CMLR dataset, when i run Unpack.py, the s2 file i found have some same name different wav files, anyone know how to solve this?

**Comment by zzj1111** [comment]
yeah I found this problem when i run Unpack.py , too.  The conclusion i found was that the bug maybe came from the original dataset CMLR. Finally i ignored these wav files with same name, for they are just a tiny fraction of this dataset. 
Anyway, If you want to solve the problem, you can ask LLM(such as ChatGPT) and give the python code to ChatGPT. I am sorry for i can't repair the code for you by myself now, because i am occupied with my final exams in university.

**Comment by Kiri0824** [comment]
Thanks! I solved the problem, just don't use s1 to s11files, use the next layer.
before:
```
--audio
   |--s1
       |--20090626
           |--section.....
           |.......
       |--20090627
       |......
   |--s2
   |......
```
change to:
```
--audio
   |--20090626
       |--section.....
       |.......
   |--20090627
   |......
```
i found that's no same name different wav files😊
